### PR TITLE
Add jonas-zipprick to the CODEOWNERS of the equinix-metal provider

### PR DESCRIPTION
**Pull request by jonas-zipprick**
**What this PR does / why we need it**:
I am going to help @schrodit to maintain this repository

### CODE REVIEW

**Comment by ghost** [comment]
@jonas-zipprick Thank you for your contribution.

**Comment by ghost** [comment]
Thank you @jonas-zipprick for your contribution. Before I can start building your PR, a member of the organization must set the required label(s) {'reviewed/ok-to-test'}. Once started, you can check the build status in the PR checks section below.

**Comment by himanshu-kun** [comment]
waiting for @schrodit approval

**Review by schrodit — APPROVED** [review]
/lgtm

**Comment by schrodit** [comment]
@himanshu-kun Jonas should also be given write access as he is otherwise not able to review PR's.

**Comment by himanshu-kun** [comment]
I am part of `mcm-maintainers` but seems like this doesn't give me `admin` privileges over this repo, so I can't grant the write access here.
@ashwani2k do you have admin privileges for this repo?

**Comment by himanshu-kun** [comment]
I will merge this PR , won't keep this blocked

**Pull request merged**
