### PR TITLE
[WIP] First cut Equinix Metal out of tree

### PR DESCRIPTION
**Pull request by deitch**
As discussed on Slack with @prashanth26 and @AxiomSamarth 

This is not properly tested. At this point, we just want to know that we are in the right direction, and what obvious mistakes we are making or things we are missing.

### CODE REVIEW

**Comment by ghost** [comment]
@deitch Thank you for your contribution.

**Comment by deitch** [comment]
This has a lot of files, mainly because it is a clean commit. Copied everything over from the template and then applied to it. I probably should make it 2 commits: the template and everything else. Maybe I will update it.

**Comment by prashanth26** [comment]
>This has a lot of files, mainly because it is a clean commit. Copied everything over from the template and then applied to it. I probably should make it 2 commits: the template and everything else. Maybe I will update it.

Thanks. Also, if it's possible to maintain the history with the `sampleProvider` repo it would be great. [Something like this. ](https://github.com/gardener/machine-controller-manager-provider-azure/commits/master?after=f07c39d3a24ea0af5a83a016e3143e26abb230e4+34&branch=master)

**Comment by deitch** [comment]
This PR got messed up completely. I am going to close it and open a new one.

**Pull request closed without merging**
