### PR TITLE
Switch to equinix sdk and remove facility usage

### LINKED ISSUE #16: Facility Deprecation
**What happened**:

Equinix Metal is deprecating facility deployment. Metros encompass multiple facilities and are a better fit for availability concerns.

Metro provisioning is largely implemented in the same way, whether for IP addresses, VLANs, or Metal servers. The `metro` field is supplied *instead of* the `facility` (or `facilities`) field. The response object will include a `metro` rather than (in some cases, in addition to) a `facility` field. Network resources previously configured in a facility are available within the metro that facility resides within. All previously 'facility' provisioned network resources are portable across the metro with respect to the Metal Project (which has always been a secondary context for network resources).

**What you expected to happen**:

The provider should more completely adapt to Metro based provisioning and remove Facility deployment options.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know**:

https://feedback.equinixmetal.com/changelog/bye-facilities-hello-again-metros

Code of interest:
- https://github.com/search?q=repo%3Agardener%2Fmachine-controller-manager-provider-equinix-metal%20ewr1&type=code
- https://github.com/search?q=repo%3Agardener%2Fmachine-controller-manager-provider-equinix-metal%20facilities&type=code

**Environment**:

Equinix Metal

* related to https://github.com/gardener/gardener-extension-provider-equinix-metal/pull/161
* https://github.com/gardener/gardener-extension-provider-equinix-metal/issues/265
* https://github.com/packethost/packngo/issues/369

### PR DESCRIPTION
**Pull request by schrodit**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #16 

**Special notes for your reviewer**:

Also switched to the newer equinix sdk as the old packet is dprecated.

**Release note**:

```feature operator
Equinix Metal is deprecating facility deployment. Metros encompass multiple facilities and are a better fit for availability concerns.
The machine controller manager is now only doing metro deployments.
Current facility deployed machines are handled as before and will be replaced with the next os or K8s update.
```

### CODE REVIEW

**Comment by ghost** [comment]
@schrodit Thank you for your contribution.

**Comment by gardener-robot-ci-2** [comment]
Thank you @schrodit for your contribution. Before I can start building your PR, a member of the organization must set the required label(s) {'reviewed/ok-to-test'}. Once started, you can check the build status in the PR checks section below.

**Comment by ghost** [comment]
@jonas-zipprick You have pull request review open invite, please check

**Pull request merged**
