### PR TITLE
Revendor `gardener/machine-controller-manager@0.47.0`

### PR DESCRIPTION
**Pull request by shafeeqes**
**What this PR does / why we need it**:
Revendor `machine-controller-manager@0.47.0`

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other dependency
The following dependency is updated:
- github.com/gardener/machine-controller-manager v0.45.0 -> 0.47.0
```

### CODE REVIEW

**Review by himanshu-kun — APPROVED** [review]
/lgtm

**Comment by rfranzke** [comment]
Can we proceed with this?

**Comment by shafeeqes** [comment]
> Can we proceed with this?

Yes.

**Comment by shafeeqes** [comment]
Can we merge and release this? @himanshu-kun

**Pull request merged**
